name: Build
on: [push, pull_request]
jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
    
    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go
      
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      
    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
      
    - name: Test
      run: go test -v -coverprofile=coverage.txt -covermode=atomic ./...

    - name: Upload Coverage
      uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: ./coverage.txt
        flags: unittests
        name: codecov-quirk

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      run: go build -v .
      
  notify:
    name: Notify
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
    
    - name: Send Notification
      env:
        EVENT: ${{github.event_name}}
        REF: ${{github.ref}}
        DISCORD_WEBHOOK: ${{secrets.DISCORD_WEBHOOK}}
      uses: Ilshidur/action-discord@0.0.2
      with:
        args: format('{0} initiated for {1}.\n[Quirk](https://github.com/damienfamed75/quirk) built and tested.\n[Pipeline](https://github.com/damienfamed75/quirk/actions)`, $EVENT, $REF)
