name: Build
on: [push, pull_request]
jobs:
  test:
    # new service with volumes.
    # save coverage in volume.
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
    
    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go
      
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      
    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
      
    - name: Test
      run: sudo go test -v -coverprofile=./.github/coverage.txt -covermode=atomic ./...

    - name: Commit Coverage
      uses: fnkr/github-action-git-bash@v1.1
      with:
        args: ["bash", "-c", "git add -a && git commit -m \"coverage updated\" && git remote set-url origin git@github.com:damienfamed75/quirk.git && git push --force origin master"]

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      run: go build -v .
  
  codecov:
    name: Code Coverage
    needs: test
    runs-on: ubuntu-latest
          
    steps:
      
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    
    - name: Upload Coverage
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: ./.github/coverage.txt
        flags: unittests
        name: codecov-quirk
  
  notify:
    name: Notify
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
    
    - name: Send Notification
      env:
        DISCORD_WEBHOOK: ${{secrets.DISCORD_WEBHOOK}}
      uses: Ilshidur/action-discord@0.0.2
